services:
  nginx:
    init: true
    container_name: container-nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - SERVER_NAME=${SERVER_NAME}
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  mariadb:
    init: true
    container_name: container-mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    networks:
      - inception
    env_file: .env
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - MARIA_PATH=${MARIA_PATH}
      - SQL_NAME_DATABASE=${SQL_NAME_DATABASE}
      - SQL_NAME_USER=${SQL_NAME_USER}
      - SQL_NAME_ADMIN=${SQL_NAME_ADMIN}
    secrets:
      - sql_password_admin
      - sql_password_user
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 30s

  wordpress:
    init: true
    container_name: container-wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    environment:
      - TITLE_OF_SITE=${TITLE_OF_SITE}
      - SERVER_NAME=${SERVER_NAME}
      - SQL_NAME_DATABASE=${SQL_NAME_DATABASE}
      - SQL_NAME_USER=${SQL_NAME_USER}
      - SQL_NAME_ADMIN=${SQL_NAME_ADMIN}
    secrets:
      - sql_password_admin
      - sql_password_user
    restart: always
    ports:
      - "9000:9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      # device: './data_docker_compose/wordpress'
      device: '/home/yzaoui/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yzaoui/data/mariadb'
      # device: './data_docker_compose/mariadb'

networks:
  inception:
    driver: bridge

secrets:
  sql_password_admin:
    file: ./../secrets/sql_password_admin.txt
  sql_password_user:
    file: ./../secrets/sql_password_user.txt
